setup-os-iso:
  needs:
    - job: guest-os-diskimg
      artifacts: false
    - job: host-os-diskimg
      artifacts: false
  extends:
    - .ubuntu-nix-docker-protected
    - .rules-parent-pipeline-autorun-on-trigger
  stage: host-os-build
  script:
    - |
      set -xeuo pipefail
      VERSION=$(git rev-parse HEAD)
      export VERSION
      echo "Build ID: ${VERSION}"

      cd "${CI_PROJECT_DIR}"/ic-os/setupos

      # NOTE: This is currently hardcoded to a specific blessed version of guestOS
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py --remote-path=guest-os --out=guestos --git-rev="${VERSION}"
      "$CI_PROJECT_DIR"/gitlab-ci/src/artifacts/rclone_download.py --remote-path=host-os --out=hostos --git-rev="${VERSION}"

      BUILD_OUT="build-out/disk-img"
      BUILD_TMP="build-tmp"
      UPLOAD_TARGET="setup-os/disk-img"

      buildevents cmd "${ROOT_PIPELINE_ID}" "${CI_JOB_ID}" build-host-img -- \
      "${CI_PROJECT_DIR}"/gitlab-ci/src/job_scripts/lib/setup-os-diskimg.sh \
        "$BUILD_OUT" "$BUILD_TMP" "$UPLOAD_TARGET" "$VERSION"

      buildevents cmd "$ROOT_PIPELINE_ID" "$CI_JOB_ID" rclone -- \
      "${CI_PROJECT_DIR}"/gitlab-ci/src/artifacts/rclone_upload.py --version="${VERSION}" "$BUILD_OUT" "$UPLOAD_TARGET"
