title = "Memory test canister alongside counter canister"
description = "Observe latency to counter canister while memory test canister is stressed"

[[workload]]
canister = "counter"
duration = 300
rps = 100

[[workload]]
canister = "memory-test-canister"
# Start 30s later
start_delay = 30
duration = 270
call_method = "update_copy"
method = "Update"
json_payload = '{"size": 5000000}'
