[package]
name = "ic-btc-library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin = "0.28.1"
ic-cdk = "0.5.1"
ic-cdk-macros = "0.5.1"
serde = "1.0.132"
async-trait = "0.1.53"
candid = "0.7.14"
ic-btc-types = { path = "../types/public" }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["full"] }
hex = "0.4.3"