[package]
name = "ic-ledger-core"
version = "0.8.0"
authors = ["The Internet Computer Project Developers"]
edition = "2018"

[dependencies]
async-trait = "0.1.53"
candid = "0.7.10"
hex = "0.4.2"
ic-base-types = { path = "../../types/base_types" }
ic-constants = { path = "../../constants" }
ic-crypto-sha = { path = "../../crypto/sha/" }
ic-ic00-types = { path = "../../types/ic00_types" }
ic-utils = { path = "../../utils" }
serde = "1.0"
serde_bytes = "0.11"
